language: node_js
dist: trusty
sudo: false

node_js:
  - '8.9.4'

addons:
  chrome: stable

branches:
  only:
  - master

install:
  - npm install

script:
  - ./build.sh

cache:
  directories:
    - ./node_modules/
