language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'

cache: yarn

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8953131954d5e41f649b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack:
    secure: EP4MzZ8JMyNQJ4S3cd5LEPWSMjC7ZRdzt3veelDiOeorJ6GwZfCDHncR+4BahDzQAuqyE/yNpZqaLbwRWloDi15qIUsm09vgl/1IyNky1Sqc6lEknhzIXpWSalo4/T9ZP8w870EoDvM/UO+LCV99R3wS8Nm9o99eLoWVb2HIUu0=

before_script:
  - yarn install --frozen-lockfile

script:
  - ./build.sh

