language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'

cache:
  directories:
    - node_modules
    - typings

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8953131954d5e41f649b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack:
    secure: EP4MzZ8JMyNQJ4S3cd5LEPWSMjC7ZRdzt3veelDiOeorJ6GwZfCDHncR+4BahDzQAuqyE/yNpZqaLbwRWloDi15qIUsm09vgl/1IyNky1Sqc6lEknhzIXpWSalo4/T9ZP8w870EoDvM/UO+LCV99R3wS8Nm9o99eLoWVb2HIUu0=

env:
  global:
  - SAUCE_ACCESS_KEY=''
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3

before_script:
  - npm install

script:
  - ./build.sh

