language: node_js
dist: trusty
sudo: false

node_js:
  - '8.9.4'

addons:
  chrome: stable

branches:
  only:
  - master

install:
  - yarn install --frozen-lockfile

script:
  - echo 'hello'

cache: yarn
