language: node_js
dist: trusty
sudo: false

node_js:
  - '8.9.4'

addons:
  chrome: stable

branches:
  only:
  - master

jobs:
  include:
    - env: "MODE=lint"
    - env: "MODE=build"
    - env: "MODE=karma"
    - env: "MODE=jasmine"

install:
  - yarn install --frozen-lockfile

script:
  - ./scripts/ci/travis-script.sh

cache: yarn
