language: node_js
node_js:
  - '4'
  - '5'

cache:
  directories:
    - node_modules
    - modules/express-engine/node_modules
    - modules/express-engine/typings
    - modules/preboot/node_modules
    - modules/preboot/typings
    - modules/grunt-prerender/node_modules
    - modules/grunt-prerender/typings
    - modules/gulp-prerender/node_modules
    - modules/gulp-prerender/typings
    - modules/hapi-engine/node_modules
    - modules/hapi-engine/typings
    - modules/universal/node_modules
    - modules/universal/typings
    - modules/webpack-prerender/node_modules
    - modules/webpack-prerender/typings
    - typings

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8953131954d5e41f649b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack:
    secure: EP4MzZ8JMyNQJ4S3cd5LEPWSMjC7ZRdzt3veelDiOeorJ6GwZfCDHncR+4BahDzQAuqyE/yNpZqaLbwRWloDi15qIUsm09vgl/1IyNky1Sqc6lEknhzIXpWSalo4/T9ZP8w870EoDvM/UO+LCV99R3wS8Nm9o99eLoWVb2HIUu0=

env:
  global:
  - SAUCE_ACCESS_KEY=''

before_install:
  - npm install -g typings

before_script:
  - npm install -g gulp

script:
  - npm run ci
