/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/app.node.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '../../../../dist/platform-node/node-platform';
import * as import5 from '../../../../dist/platform-node/node-http';
import * as import6 from '../../../../dist/universal/node/universal-module';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '../../../../dist/platform-node/node-shared-styles-host';
import * as import15 from '../../../../dist/platform-node/node-renderer';
import * as import16 from '@angular/core/src/linker/view_utils';
import * as import17 from '../../../../dist/platform-node/node-location';
import * as import18 from '../../../../dist/platform-node/__private_imports__';
import * as import19 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import20 from '@angular/http/src/base_request_options';
import * as import21 from '@angular/http/src/base_response_options';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/core/src/di/injector';
import * as import24 from './app/index.ngfactory';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from '@angular/core/src/security';
import * as import27 from '@angular/core/src/console';
import * as import28 from '@angular/core/src/i18n/tokens';
import * as import29 from '@angular/core/src/error_handler';
import * as import30 from '@angular/core/src/application_tokens';
import * as import31 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import32 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import33 from '@angular/platform-browser/src/dom/animation_driver';
import * as import34 from '@angular/core/src/render/api';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import37 from '../../../../dist/platform-node/tokens';
import * as import38 from '@angular/common/src/location/location_strategy';
import * as import39 from '@angular/common/src/location/platform_location';
import * as import40 from '@angular/http/src/backends/xhr_backend';
import * as import41 from '@angular/http/src/http';
import * as import42 from '@angular/http/src/backends/jsonp_backend';
class MainNodeModuleInjector extends import0.NgModuleInjector<import1.MainNodeModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _NodeModule_2:import4.NodeModule;
  _NodeHttpModule_3:import5.NodeHttpModule;
  _NodeJsonpModule_4:import5.NodeJsonpModule;
  _UniversalModule_5:import6.UniversalModule;
  _InternalFormsSharedModule_6:import7.InternalFormsSharedModule;
  _FormsModule_7:import8.FormsModule;
  _MainNodeModule_8:import1.MainNodeModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import10.ApplicationInitStatus;
  _TestabilityRegistry_13:import4.MockTestabilityRegistry;
  _Testability_14:import11.Testability;
  _ApplicationRef__15:import12.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import13.Compiler;
  __APP_ID_18:any;
  __NodeSharedStylesHost_19:import14.NodeSharedStylesHost;
  __DOCUMENT_20:any;
  __NodeDomEventsPlugin_21:import4.NodeDomEventsPlugin;
  __EVENT_MANAGER_PLUGINS_22:any[];
  __NodeEventManager_23:import4.NodeEventManager;
  __EventManager_24:any;
  __AnimationDriver_25:any;
  __NodeDomRootRenderer_26:import15.NodeDomRootRenderer;
  __DomRootRenderer_27:any;
  __RootRenderer_28:any;
  __ViewUtils_29:import16.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __ORIGIN_URL_32:any;
  __REQUEST_URL_33:any;
  __APP_BASE_HREF_34:any;
  __PlatformLocation_35:import17.NodePlatformLocation;
  __BROWSER_SANITIZATION_PROVIDERS_36:import18.BROWSER_SANITIZATION_PROVIDERS;
  __DomEventsPlugin_37:any[];
  __HAMMER_GESTURE_CONFIG_38:import19.HammerGestureConfig;
  __SharedStylesHost_39:any;
  __DomSharedStylesHost_40:any;
  __RequestOptions_41:import20.BaseRequestOptions;
  __ResponseOptions_42:import21.BaseResponseOptions;
  __XHRBackend_43:import5.NodeBackend;
  __Http_44:any;
  __JSONPBackend_45:import5.NodeJsonpBackend_;
  __Jsonp_46:any;
  __RadioControlRegistry_47:import22.RadioControlRegistry;
  constructor(parent:import23.Injector) {
    super(parent,[import24.AppNgFactory],[import24.AppNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == (null as any))) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == (null as any))) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == (null as any))) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import13.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import13.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = '%cmp%'); }
    return this.__APP_ID_18;
  }
  get _NodeSharedStylesHost_19():import14.NodeSharedStylesHost {
    if ((this.__NodeSharedStylesHost_19 == (null as any))) { (this.__NodeSharedStylesHost_19 = new import14.NodeSharedStylesHost()); }
    return this.__NodeSharedStylesHost_19;
  }
  get _DOCUMENT_20():any {
    if ((this.__DOCUMENT_20 == (null as any))) { (this.__DOCUMENT_20 = import4._document(this._NodeSharedStylesHost_19,this.parent.get(import25.NgZone))); }
    return this.__DOCUMENT_20;
  }
  get _NodeDomEventsPlugin_21():import4.NodeDomEventsPlugin {
    if ((this.__NodeDomEventsPlugin_21 == (null as any))) { (this.__NodeDomEventsPlugin_21 = new import4.NodeDomEventsPlugin()); }
    return this.__NodeDomEventsPlugin_21;
  }
  get _EVENT_MANAGER_PLUGINS_22():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_22 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_22 = [
      this._NodeDomEventsPlugin_21,
      new import18.KeyEventsPlugin(),
      new import18.HammerGesturesPlugin()
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_22;
  }
  get _NodeEventManager_23():import4.NodeEventManager {
    if ((this.__NodeEventManager_23 == (null as any))) { (this.__NodeEventManager_23 = new import4.NodeEventManager(this._EVENT_MANAGER_PLUGINS_22,this._DOCUMENT_20,this.parent.get(import25.NgZone))); }
    return this.__NodeEventManager_23;
  }
  get _EventManager_24():any {
    if ((this.__EventManager_24 == (null as any))) { (this.__EventManager_24 = this._NodeEventManager_23); }
    return this.__EventManager_24;
  }
  get _AnimationDriver_25():any {
    if ((this.__AnimationDriver_25 == (null as any))) { (this.__AnimationDriver_25 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_25;
  }
  get _NodeDomRootRenderer_26():import15.NodeDomRootRenderer {
    if ((this.__NodeDomRootRenderer_26 == (null as any))) { (this.__NodeDomRootRenderer_26 = new import15.NodeDomRootRenderer(this._DOCUMENT_20,this._EventManager_24,this._NodeSharedStylesHost_19,this._AnimationDriver_25)); }
    return this.__NodeDomRootRenderer_26;
  }
  get _DomRootRenderer_27():any {
    if ((this.__DomRootRenderer_27 == (null as any))) { (this.__DomRootRenderer_27 = this._NodeDomRootRenderer_26); }
    return this.__DomRootRenderer_27;
  }
  get _RootRenderer_28():any {
    if ((this.__RootRenderer_28 == (null as any))) { (this.__RootRenderer_28 = this._DomRootRenderer_27); }
    return this.__RootRenderer_28;
  }
  get _ViewUtils_29():import16.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import16.ViewUtils(this._RootRenderer_28,this._APP_ID_18,this.parent.get(import26.Sanitizer))); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _ORIGIN_URL_32():any {
    if ((this.__ORIGIN_URL_32 == (null as any))) { (this.__ORIGIN_URL_32 = import4._ORIGIN_URL(this.parent.get(import25.NgZone))); }
    return this.__ORIGIN_URL_32;
  }
  get _REQUEST_URL_33():any {
    if ((this.__REQUEST_URL_33 == (null as any))) { (this.__REQUEST_URL_33 = import4._REQUEST_URL(this.parent.get(import25.NgZone))); }
    return this.__REQUEST_URL_33;
  }
  get _APP_BASE_HREF_34():any {
    if ((this.__APP_BASE_HREF_34 == (null as any))) { (this.__APP_BASE_HREF_34 = import4._APP_BASE_HREF(this.parent.get(import25.NgZone))); }
    return this.__APP_BASE_HREF_34;
  }
  get _PlatformLocation_35():import17.NodePlatformLocation {
    if ((this.__PlatformLocation_35 == (null as any))) { (this.__PlatformLocation_35 = new import17.NodePlatformLocation(this._ORIGIN_URL_32,this._REQUEST_URL_33,this._APP_BASE_HREF_34)); }
    return this.__PlatformLocation_35;
  }
  get _BROWSER_SANITIZATION_PROVIDERS_36():import18.BROWSER_SANITIZATION_PROVIDERS {
    if ((this.__BROWSER_SANITIZATION_PROVIDERS_36 == (null as any))) { (this.__BROWSER_SANITIZATION_PROVIDERS_36 = new import18.BROWSER_SANITIZATION_PROVIDERS()); }
    return this.__BROWSER_SANITIZATION_PROVIDERS_36;
  }
  get _DomEventsPlugin_37():any[] {
    if ((this.__DomEventsPlugin_37 == (null as any))) { (this.__DomEventsPlugin_37 = [this._NodeDomEventsPlugin_21]); }
    return this.__DomEventsPlugin_37;
  }
  get _HAMMER_GESTURE_CONFIG_38():import19.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_38 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_38 = new import19.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_38;
  }
  get _SharedStylesHost_39():any {
    if ((this.__SharedStylesHost_39 == (null as any))) { (this.__SharedStylesHost_39 = this._NodeSharedStylesHost_19); }
    return this.__SharedStylesHost_39;
  }
  get _DomSharedStylesHost_40():any {
    if ((this.__DomSharedStylesHost_40 == (null as any))) { (this.__DomSharedStylesHost_40 = this._NodeSharedStylesHost_19); }
    return this.__DomSharedStylesHost_40;
  }
  get _RequestOptions_41():import20.BaseRequestOptions {
    if ((this.__RequestOptions_41 == (null as any))) { (this.__RequestOptions_41 = new import20.BaseRequestOptions()); }
    return this.__RequestOptions_41;
  }
  get _ResponseOptions_42():import21.BaseResponseOptions {
    if ((this.__ResponseOptions_42 == (null as any))) { (this.__ResponseOptions_42 = new import21.BaseResponseOptions()); }
    return this.__ResponseOptions_42;
  }
  get _XHRBackend_43():import5.NodeBackend {
    if ((this.__XHRBackend_43 == (null as any))) { (this.__XHRBackend_43 = new import5.NodeBackend(this._ResponseOptions_42,this.parent.get(import25.NgZone),this._APP_BASE_HREF_34,this._ORIGIN_URL_32)); }
    return this.__XHRBackend_43;
  }
  get _Http_44():any {
    if ((this.__Http_44 == (null as any))) { (this.__Http_44 = import5.httpFactory(this._XHRBackend_43,this._RequestOptions_41)); }
    return this.__Http_44;
  }
  get _JSONPBackend_45():import5.NodeJsonpBackend_ {
    if ((this.__JSONPBackend_45 == (null as any))) { (this.__JSONPBackend_45 = new import5.NodeJsonpBackend_(this._ResponseOptions_42,this.parent.get(import25.NgZone),this._APP_BASE_HREF_34,this._ORIGIN_URL_32)); }
    return this.__JSONPBackend_45;
  }
  get _Jsonp_46():any {
    if ((this.__Jsonp_46 == (null as any))) { (this.__Jsonp_46 = import5.jsonpFactory(this._JSONPBackend_45,this._RequestOptions_41)); }
    return this.__Jsonp_46;
  }
  get _RadioControlRegistry_47():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_47 == (null as any))) { (this.__RadioControlRegistry_47 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_47;
  }
  createInternal():import1.MainNodeModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._NodeModule_2 = new import4.NodeModule(this.parent.get(import4.NodeModule,(null as any)));
    this._NodeHttpModule_3 = new import5.NodeHttpModule();
    this._NodeJsonpModule_4 = new import5.NodeJsonpModule();
    this._UniversalModule_5 = new import6.UniversalModule();
    this._InternalFormsSharedModule_6 = new import7.InternalFormsSharedModule();
    this._FormsModule_7 = new import8.FormsModule();
    this._MainNodeModule_8 = new import1.MainNodeModule();
    this._ErrorHandler_11 = import4._errorHandler();
    this._ApplicationInitStatus_12 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._TestabilityRegistry_13 = new import4.MockTestabilityRegistry();
    this._Testability_14 = new import11.Testability(this.parent.get(import25.NgZone));
    this._ApplicationRef__15 = new import12.ApplicationRef_(this.parent.get(import25.NgZone),this.parent.get(import27.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this._TestabilityRegistry_13,this._Testability_14);
    return this._MainNodeModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.NodeModule)) { return this._NodeModule_2; }
    if ((token === import5.NodeHttpModule)) { return this._NodeHttpModule_3; }
    if ((token === import5.NodeJsonpModule)) { return this._NodeJsonpModule_4; }
    if ((token === import6.UniversalModule)) { return this._UniversalModule_5; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_6; }
    if ((token === import8.FormsModule)) { return this._FormsModule_7; }
    if ((token === import1.MainNodeModule)) { return this._MainNodeModule_8; }
    if ((token === import28.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import29.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import11.TestabilityRegistry)) { return this._TestabilityRegistry_13; }
    if ((token === import11.Testability)) { return this._Testability_14; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import13.Compiler)) { return this._Compiler_17; }
    if ((token === import30.APP_ID)) { return this._APP_ID_18; }
    if ((token === import14.NodeSharedStylesHost)) { return this._NodeSharedStylesHost_19; }
    if ((token === import31.DOCUMENT)) { return this._DOCUMENT_20; }
    if ((token === import4.NodeDomEventsPlugin)) { return this._NodeDomEventsPlugin_21; }
    if ((token === import32.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_22; }
    if ((token === import4.NodeEventManager)) { return this._NodeEventManager_23; }
    if ((token === import32.EventManager)) { return this._EventManager_24; }
    if ((token === import33.AnimationDriver)) { return this._AnimationDriver_25; }
    if ((token === import15.NodeDomRootRenderer)) { return this._NodeDomRootRenderer_26; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_27; }
    if ((token === import34.RootRenderer)) { return this._RootRenderer_28; }
    if ((token === import16.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import35.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import36.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import37.ORIGIN_URL)) { return this._ORIGIN_URL_32; }
    if ((token === import37.REQUEST_URL)) { return this._REQUEST_URL_33; }
    if ((token === import38.APP_BASE_HREF)) { return this._APP_BASE_HREF_34; }
    if ((token === import39.PlatformLocation)) { return this._PlatformLocation_35; }
    if ((token === import18.BROWSER_SANITIZATION_PROVIDERS)) { return this._BROWSER_SANITIZATION_PROVIDERS_36; }
    if ((token === import18.DomEventsPlugin)) { return this._DomEventsPlugin_37; }
    if ((token === import19.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_38; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_39; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_40; }
    if ((token === import20.RequestOptions)) { return this._RequestOptions_41; }
    if ((token === import21.ResponseOptions)) { return this._ResponseOptions_42; }
    if ((token === import40.XHRBackend)) { return this._XHRBackend_43; }
    if ((token === import41.Http)) { return this._Http_44; }
    if ((token === import42.JSONPBackend)) { return this._JSONPBackend_45; }
    if ((token === import41.Jsonp)) { return this._Jsonp_46; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_47; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
  }
}
export const MainNodeModuleNgFactory:import0.NgModuleFactory<import1.MainNodeModule> = new import0.NgModuleFactory(MainNodeModuleInjector,import1.MainNodeModule);