/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/app.browser.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '../../../../dist/universal/browser/universal-module';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import17 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/core/src/linker/view_utils';
import * as import20 from '@angular/platform-browser/src/browser/title';
import * as import21 from '@angular/http/src/backends/browser_xhr';
import * as import22 from '@angular/http/src/base_response_options';
import * as import23 from '@angular/http/src/backends/xhr_backend';
import * as import24 from '@angular/http/src/base_request_options';
import * as import25 from '@angular/http/src/backends/browser_jsonp';
import * as import26 from '@angular/http/src/backends/jsonp_backend';
import * as import27 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import28 from '@angular/core/src/di/injector';
import * as import29 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import30 from '@angular/platform-browser/src/dom/events/key_events';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import33 from '@angular/core/src/console';
import * as import34 from '@angular/core/src/i18n/tokens';
import * as import35 from '@angular/core/src/error_handler';
import * as import36 from '@angular/core/src/application_tokens';
import * as import37 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import38 from '@angular/platform-browser/src/dom/animation_driver';
import * as import39 from '@angular/core/src/render/api';
import * as import40 from '@angular/core/src/security';
import * as import41 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import42 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import43 from '@angular/http/src/interfaces';
import * as import44 from '@angular/http/src/http';
class MainBrowserModuleInjector extends import0.NgModuleInjector<import1.MainBrowserModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _JsonpModule_4:import5.JsonpModule;
  _UniversalModule_5:import6.UniversalModule;
  _InternalFormsSharedModule_6:import7.InternalFormsSharedModule;
  _FormsModule_7:import8.FormsModule;
  _MainBrowserModule_8:import1.MainBrowserModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import10.ApplicationInitStatus;
  _Testability_13:import11.Testability;
  _ApplicationRef__14:import12.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import13.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import14.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import15.EventManager;
  __DomSharedStylesHost_22:import16.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import17.DomRootRenderer_;
  __RootRenderer_25:any;
  __DomSanitizer_26:import18.DomSanitizerImpl;
  __Sanitizer_27:any;
  __ViewUtils_28:import19.ViewUtils;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __SharedStylesHost_31:any;
  __Title_32:import20.Title;
  __BrowserXhr_33:import21.BrowserXhr;
  __ResponseOptions_34:import22.BaseResponseOptions;
  __XSRFStrategy_35:any;
  __XHRBackend_36:import23.XHRBackend;
  __RequestOptions_37:import24.BaseRequestOptions;
  __Http_38:any;
  __BrowserJsonp_39:import25.BrowserJsonp;
  __JSONPBackend_40:import26.JSONPBackend_;
  __Jsonp_41:any;
  __UNIVERSAL_CACHE_42:any;
  __AUTO_PREBOOT_43:any;
  __APP_BOOTSTRAP_LISTENER_44:any[];
  __RadioControlRegistry_45:import27.RadioControlRegistry;
  constructor(parent:import28.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == (null as any))) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == (null as any))) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == (null as any))) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import13.Compiler {
    if ((this.__Compiler_16 == (null as any))) { (this.__Compiler_16 = new import13.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == (null as any))) { (this.__APP_ID_17 = import6.appIdFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == (null as any))) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import14.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_19 = new import14.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import29.DomEventsPlugin(),
      new import30.KeyEventsPlugin(),
      new import14.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import15.EventManager {
    if ((this.__EventManager_21 == (null as any))) { (this.__EventManager_21 = new import15.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import31.NgZone))); }
    return this.__EventManager_21;
  }
  get _DomSharedStylesHost_22():import16.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_22 == (null as any))) { (this.__DomSharedStylesHost_22 = new import16.DomSharedStylesHost(this._DOCUMENT_18)); }
    return this.__DomSharedStylesHost_22;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == (null as any))) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import17.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == (null as any))) { (this.__DomRootRenderer_24 = new import17.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23)); }
    return this.__DomRootRenderer_24;
  }
  get _RootRenderer_25():any {
    if ((this.__RootRenderer_25 == (null as any))) { (this.__RootRenderer_25 = import32._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import32.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_25;
  }
  get _DomSanitizer_26():import18.DomSanitizerImpl {
    if ((this.__DomSanitizer_26 == (null as any))) { (this.__DomSanitizer_26 = new import18.DomSanitizerImpl()); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == (null as any))) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _ViewUtils_28():import19.ViewUtils {
    if ((this.__ViewUtils_28 == (null as any))) { (this.__ViewUtils_28 = new import19.ViewUtils(this._RootRenderer_25,this._APP_ID_17,this._Sanitizer_27)); }
    return this.__ViewUtils_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == (null as any))) { (this.__IterableDiffers_29 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == (null as any))) { (this.__KeyValueDiffers_30 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_30;
  }
  get _SharedStylesHost_31():any {
    if ((this.__SharedStylesHost_31 == (null as any))) { (this.__SharedStylesHost_31 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_31;
  }
  get _Title_32():import20.Title {
    if ((this.__Title_32 == (null as any))) { (this.__Title_32 = new import20.Title()); }
    return this.__Title_32;
  }
  get _BrowserXhr_33():import21.BrowserXhr {
    if ((this.__BrowserXhr_33 == (null as any))) { (this.__BrowserXhr_33 = new import21.BrowserXhr()); }
    return this.__BrowserXhr_33;
  }
  get _ResponseOptions_34():import22.BaseResponseOptions {
    if ((this.__ResponseOptions_34 == (null as any))) { (this.__ResponseOptions_34 = new import22.BaseResponseOptions()); }
    return this.__ResponseOptions_34;
  }
  get _XSRFStrategy_35():any {
    if ((this.__XSRFStrategy_35 == (null as any))) { (this.__XSRFStrategy_35 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_35;
  }
  get _XHRBackend_36():import23.XHRBackend {
    if ((this.__XHRBackend_36 == (null as any))) { (this.__XHRBackend_36 = new import23.XHRBackend(this._BrowserXhr_33,this._ResponseOptions_34,this._XSRFStrategy_35)); }
    return this.__XHRBackend_36;
  }
  get _RequestOptions_37():import24.BaseRequestOptions {
    if ((this.__RequestOptions_37 == (null as any))) { (this.__RequestOptions_37 = new import24.BaseRequestOptions()); }
    return this.__RequestOptions_37;
  }
  get _Http_38():any {
    if ((this.__Http_38 == (null as any))) { (this.__Http_38 = import5.httpFactory(this._XHRBackend_36,this._RequestOptions_37)); }
    return this.__Http_38;
  }
  get _BrowserJsonp_39():import25.BrowserJsonp {
    if ((this.__BrowserJsonp_39 == (null as any))) { (this.__BrowserJsonp_39 = new import25.BrowserJsonp()); }
    return this.__BrowserJsonp_39;
  }
  get _JSONPBackend_40():import26.JSONPBackend_ {
    if ((this.__JSONPBackend_40 == (null as any))) { (this.__JSONPBackend_40 = new import26.JSONPBackend_(this._BrowserJsonp_39,this._ResponseOptions_34)); }
    return this.__JSONPBackend_40;
  }
  get _Jsonp_41():any {
    if ((this.__Jsonp_41 == (null as any))) { (this.__Jsonp_41 = import5.jsonpFactory(this._JSONPBackend_40,this._RequestOptions_37)); }
    return this.__Jsonp_41;
  }
  get _UNIVERSAL_CACHE_42():any {
    if ((this.__UNIVERSAL_CACHE_42 == (null as any))) { (this.__UNIVERSAL_CACHE_42 = import6.universalCacheFactory()); }
    return this.__UNIVERSAL_CACHE_42;
  }
  get _AUTO_PREBOOT_43():any {
    if ((this.__AUTO_PREBOOT_43 == (null as any))) { (this.__AUTO_PREBOOT_43 = true); }
    return this.__AUTO_PREBOOT_43;
  }
  get _APP_BOOTSTRAP_LISTENER_44():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_44 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_44 = [import6.appBootstrapListenerFactory(this._AUTO_PREBOOT_43)]); }
    return this.__APP_BOOTSTRAP_LISTENER_44;
  }
  get _RadioControlRegistry_45():import27.RadioControlRegistry {
    if ((this.__RadioControlRegistry_45 == (null as any))) { (this.__RadioControlRegistry_45 = new import27.RadioControlRegistry()); }
    return this.__RadioControlRegistry_45;
  }
  createInternal():import1.MainBrowserModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._JsonpModule_4 = new import5.JsonpModule();
    this._UniversalModule_5 = new import6.UniversalModule(this.parent.get(import16.SharedStylesHost));
    this._InternalFormsSharedModule_6 = new import7.InternalFormsSharedModule();
    this._FormsModule_7 = new import8.FormsModule();
    this._MainBrowserModule_8 = new import1.MainBrowserModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import11.Testability(this.parent.get(import31.NgZone));
    this._ApplicationRef__14 = new import12.ApplicationRef_(this.parent.get(import31.NgZone),this.parent.get(import33.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import11.TestabilityRegistry,(null as any)),this._Testability_13);
    return this._MainBrowserModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import5.JsonpModule)) { return this._JsonpModule_4; }
    if ((token === import6.UniversalModule)) { return this._UniversalModule_5; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_6; }
    if ((token === import8.FormsModule)) { return this._FormsModule_7; }
    if ((token === import1.MainBrowserModule)) { return this._MainBrowserModule_8; }
    if ((token === import34.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import35.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import11.Testability)) { return this._Testability_13; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import13.Compiler)) { return this._Compiler_16; }
    if ((token === import36.APP_ID)) { return this._APP_ID_17; }
    if ((token === import37.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import14.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import15.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import15.EventManager)) { return this._EventManager_21; }
    if ((token === import16.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import38.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import17.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import39.RootRenderer)) { return this._RootRenderer_25; }
    if ((token === import18.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import40.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import19.ViewUtils)) { return this._ViewUtils_28; }
    if ((token === import41.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import42.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import16.SharedStylesHost)) { return this._SharedStylesHost_31; }
    if ((token === import20.Title)) { return this._Title_32; }
    if ((token === import21.BrowserXhr)) { return this._BrowserXhr_33; }
    if ((token === import22.ResponseOptions)) { return this._ResponseOptions_34; }
    if ((token === import43.XSRFStrategy)) { return this._XSRFStrategy_35; }
    if ((token === import23.XHRBackend)) { return this._XHRBackend_36; }
    if ((token === import24.RequestOptions)) { return this._RequestOptions_37; }
    if ((token === import44.Http)) { return this._Http_38; }
    if ((token === import25.BrowserJsonp)) { return this._BrowserJsonp_39; }
    if ((token === import26.JSONPBackend)) { return this._JSONPBackend_40; }
    if ((token === import44.Jsonp)) { return this._Jsonp_41; }
    if ((token === import6.UNIVERSAL_CACHE)) { return this._UNIVERSAL_CACHE_42; }
    if ((token === import6.AUTO_PREBOOT)) { return this._AUTO_PREBOOT_43; }
    if ((token === import36.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_44; }
    if ((token === import27.RadioControlRegistry)) { return this._RadioControlRegistry_45; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
  }
}
export const MainBrowserModuleNgFactory:import0.NgModuleFactory<import1.MainBrowserModule> = new import0.NgModuleFactory(MainBrowserModuleInjector,import1.MainBrowserModule);