/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../src/app/index';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/forms/src/directives/default_value_accessor';
import * as import12 from '@angular/forms/src/directives/ng_model';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/common/src/pipes/json_pipe';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_control';
var renderType_Wat_Host:import0.RenderComponentType = (null as any);
class _View_Wat_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Wat_0_4:import3.Wat;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Wat_Host0,renderType_Wat_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('wat',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Wat0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Wat_0_4 = new import3.Wat();
    this._appEl_0.initComponent(this._Wat_0_4,[],compView_0);
    compView_0.create(this._Wat_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Wat) && (0 === requestNodeIndex))) { return this._Wat_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Wat_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Wat_Host === (null as any))) { (renderType_Wat_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_Wat_Host0(viewUtils,parentInjector,declarationEl);
}
export const WatNgFactory:import9.ComponentFactory<import3.Wat> = new import9.ComponentFactory<import3.Wat>('wat',viewFactory_Wat_Host0,import3.Wat);
const styles_Wat:any[] = ['div[_ngcontent-%COMP%] {\n      background-color: red;\n    }'];
var renderType_Wat:import0.RenderComponentType = (null as any);
class _View_Wat0 extends import1.AppView<import3.Wat> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Wat0,renderType_Wat,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n      Hello World\n    ',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_Wat0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Wat> {
  if ((renderType_Wat === (null as any))) { (renderType_Wat = viewUtils.createRenderComponentType('/Users/patrickjs/Code/angular/universal/examples/express-aot/src/app/index.ts class Wat - inline template',0,import8.ViewEncapsulation.Emulated,styles_Wat,{})); }
  return new _View_Wat0(viewUtils,parentInjector,declarationEl);
}
var renderType_App_Host:import0.RenderComponentType = (null as any);
class _View_App_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _App_0_4:import3.App;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_App_Host0,renderType_App_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_App0(this.viewUtils,this.injector(0),this._appEl_0);
    this._App_0_4 = new import3.App(this.parentInjector.get(import10.Http));
    this._appEl_0.initComponent(this._App_0_4,[],compView_0);
    compView_0.create(this._App_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.App) && (0 === requestNodeIndex))) { return this._App_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._App_0_4.ngAfterViewInit(); } }
  }
}
function viewFactory_App_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_App_Host === (null as any))) { (renderType_App_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_App_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppNgFactory:import9.ComponentFactory<import3.App> = new import9.ComponentFactory<import3.App>('app',viewFactory_App_Host0,import3.App);
const styles_App:any[] = ['div[_ngcontent-%COMP%] {\n      background-color: green;\n    }'];
var renderType_App:import0.RenderComponentType = (null as any);
class _View_App0 extends import1.AppView<import3.App> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import11.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_23_4:any[];
  _NgModel_23_5:import12.NgModel;
  _NgControl_23_6:any;
  _NgControlStatus_23_7:import13.NgControlStatus;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import14.NgIf;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _pipe_json_0:import15.JsonPipe;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_App0,renderType_App,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'hello world!!!',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'pre',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'id','myid-1');
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'id','myid-2');
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'id','myid-3');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'input',(null as any));
    this.renderer.setElementAttribute(this._el_15,'oh-hai','');
    this._text_16 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'div',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'div',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_23,'id','myInput');
    this._DefaultValueAccessor_23_3 = new import11.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_23));
    this._NG_VALUE_ACCESSOR_23_4 = [this._DefaultValueAccessor_23_3];
    this._NgModel_23_5 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_23_4);
    this._NgControl_23_6 = this._NgModel_23_5;
    this._NgControlStatus_23_7 = new import13.NgControlStatus(this._NgControl_23_6);
    this._text_24 = this.renderer.createText(this._el_21,'',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._appEl_25 = new import2.AppElement(25,21,this,this._anchor_25);
    this._TemplateRef_25_5 = new import17.TemplateRef_(this._appEl_25,viewFactory_App1);
    this._NgIf_25_6 = new import14.NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_21,'button',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Wat',(null as any));
    this._text_29 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_19,'\n  ',(null as any));
    this._pipe_json_0 = new import15.JsonPipe();
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_23,'ngModelChange',this.eventHandler(this._handle_ngModelChange_23_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_23,'input',this.eventHandler(this._handle_input_23_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_23,'blur',this.eventHandler(this._handle_blur_23_2.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_23_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_23_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_4; }
    if (((token === import12.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_5; }
    if (((token === import19.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_6; }
    if (((token === import13.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_7; }
    if (((token === import17.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import14.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    changes = (null as any);
    const currVal_5:any = this.context.wat;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgModel_23_5.model = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._NgModel_23_5.ngOnChanges(changes); }
    const currVal_13:any = this.context.toggle;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgIf_25_6.ngIf = currVal_13;
      this._expr_13 = currVal_13;
    }
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_json_0.transform(this.context.response)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'lololwit';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_15,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_6:any = this._NgControlStatus_23_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_23_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_23_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_23_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_23_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_23_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import4.interpolate(1,'\n      Hello World\n      ',this.context.wat,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_24,currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_23_5.ngOnDestroy();
  }
  private _handle_ngModelChange_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.wat = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_23_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_23_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_23_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_23_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onWat($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_App0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.App> {
  if ((renderType_App === (null as any))) { (renderType_App = viewUtils.createRenderComponentType('/Users/patrickjs/Code/angular/universal/examples/express-aot/src/app/index.ts class App - inline template',0,import8.ViewEncapsulation.Emulated,styles_App,{})); }
  return new _View_App0(viewUtils,parentInjector,declarationEl);
}
class _View_App1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Wat_2_4:import3.Wat;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_App1,renderType_App,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'wat',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = viewFactory_Wat0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Wat_2_4 = new import3.Wat();
    this._appEl_2.initComponent(this._Wat_2_4,[],compView_2);
    compView_2.create(this._Wat_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Wat) && (2 === requestNodeIndex))) { return this._Wat_2_4; }
    return notFoundResult;
  }
}
function viewFactory_App1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_App1(viewUtils,parentInjector,declarationEl);
}