name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@886dc665ae52127bace968fb4ef95eb6022de753
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
