name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@36d587a0d6146bddbbd0553ef392e8bc96ab3e13
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
