name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@47168baf0b140436ad30c923ba8de24cad0aefc2
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
