name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@7679cff885633cd33bf5ac7922a5304e8971a5a6
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
