name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@583c3cf48eb8cc08248fa813795b02cbead6da31
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
