name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@885008c8215ce0254ba191ae0cfa01b43c815405
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
