name: Lock Inactive Issues

# Declare default permissions as read only.
permissions:
  contents: read

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@35ae2e0bb0fa945677d472019c7fd15511f3fd43
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
