name: Lock Inactive Issues

# Declare default permissions as read only.
permissions:
  contents: read

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@3238f034456be0ac0fbc94a3333b4ba82a8cbacf
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
