name: Lock Inactive Issues

# Declare default permissions as read only.
permissions:
  contents: read

on:
  schedule:
    # Run at 08:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@bf4bb09bb2d32015f71943371c7484cb845f8c33
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
