name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@87bb3f4dc80be571352ae1cec991cd556a2a9002
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
