name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@cce6d07bb4a1c0c3ff19aea614253164f05ec564
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
