name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@08a2c774d5ff549e09d92dea00d8a7bbfdf6e8dc
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
