name: Lock closed inactive issues

on:
  schedule:
    # Run at 8:00 every day
    - cron: '0 8 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@74b89a46292330ba949652680c30b0280249db74
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
